[build]
target = "./src/arch/x86/i386-unknown-none.json"

[target.i386-unknown-none]
rustflags = [
	"-C", "link-arg=-T./src/arch/x86/linker.ld",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = false
